# Cargo configuration for TB Language cross-compilation

# Android targets configuration
[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"

# iOS targets configuration
[target.aarch64-apple-ios]
# iOS device (ARM64)

[target.x86_64-apple-ios]
# iOS simulator (Intel)

[target.aarch64-apple-ios-sim]
# iOS simulator (Apple Silicon)

# Build settings
[build]
# Uncomment to set default target
# target = "x86_64-unknown-linux-gnu"

# Environment variables for Android NDK
# Set ANDROID_NDK_HOME environment variable to your NDK path
# Example: export ANDROID_NDK_HOME=/path/to/android-ndk

[env]
# Uncomment and set your Android NDK path
# ANDROID_NDK_HOME = "/path/to/android-ndk"

