site_name: ToolBoxV2 Docs

site_url: https://MarkinHaus.github.io/ToolBoxV2
repo_url: https://github.com/MarkinHaus/ToolBoxV2

repo_name: ToolBoxV2

theme:
    palette:
        scheme: slate
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

    extra_css:
        - assets/stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: false   # keine störenden Zeilennummern
    - toc:
        permalink: true
    - codehilite:
        use_pygments: true
        pygments_style: monokai  # alternativ: 'gruvbox-dark'
        noclasses: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["toolboxv2"]


nav:
    -   Home: index.md
    -   Installation: installation.md
    -   Usage: usage.md
    -   Contributing: contributing.md
    -   FAQ: module_creation_guide.md
    -   TBjs: tbjs.md
    -   CLIS: clis.md
    -   Report Issues: https://github.com/MarkinHaus/ToolBoxV2/issues
    -   API Reference:
            -   toolboxv2: toolboxv2.md
            -   utils: utils.md
            -   isaa: isaa.md
            -   agent: agent.md
            -   isaa_help: faq.md

    - etc:
          - account_management: account_management.md
          - changelog: changelog.md
          - db_usage_guide: db_usage_guide.md
          - p2p_rpc_protocol: p2p_rpc_protocol.md
          - stack: stack.md
