site_name: ToolBoxV2 Docs

site_url: https://MarkinHaus.github.io/ToolBoxV2
repo_url: https://github.com/MarkinHaus/ToolBoxV2

repo_name: ToolBoxV2

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    -   pymdownx.highlight:
            linenums: true
    -   toc:
            permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["toolboxv2"]


nav:
    -   Home: index.md
    -   Installation: installation.md
    -   Usage: usage.md
    -   Contributing: contributing.md
    -   FAQ: faq.md
    -   Changelog: changelog.md
    -   Report Issues: https://github.com/MarkinHaus/ToolBoxV2/issues
    -   API Reference:
            -   toolboxv2 module: toolboxv2.md
            -   utils: utils.md
