[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "r_blob_db"
version = "0.1.0"
description = "A Rust implementation of an in-memory key-value database with blob storage"
requires-python = ">=3.10"

[tool.maturin]
features = ["pyo3/extension-module"]