# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from toolboxv2 import App, get_app
from typing import Any, Dict, List, Optional
import asyncio
import json
import os
import sys
import traceback

_GLOBAL_APP: Optional[App] = None
_INSTANCE_ID: str = 'nuitka_global'
def init_app(instance_id: str) -> Dict[str, Any]:
    ...

def get_app() -> App:
    ...

def reset_app() -> Dict[str, Any]:
    ...

def call_module_function(module_name: str, function_name: str, args: Optional[List], kwargs: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    ...

def _convert_result_to_api_result(result: Any, module_name: str, function_name: str) -> Dict[str, Any]:
    ...

def get_loaded_modules() -> Dict[str, Any]:
    ...

def health_check() -> Dict[str, Any]:
    ...

_RUST_WS_BRIDGE_ENABLED = False
def enable_rust_ws_bridge() -> Dict[str, Any]:
    ...

def ws_send_message(conn_id: str, payload: str) -> Any:
    ...

def ws_broadcast_message(channel_id: str, payload: str, source_conn_id: str) -> Any:
    ...

def get_app_info() -> Dict[str, Any]:
    ...

def json_call(json_str: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import os
import ntpath
import traceback
import json
import typing
import asyncio
import toolboxv2
import pywintypes
import toolboxv2.__main__
import requests