"""Automatic generated by ToolBox v = 0.1.6"""
from enum import Enum
from dataclasses import dataclass





@dataclass
class CLI_FUNCTIONS(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'


@dataclass
class DB(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	PRIVATE: str = 'private'


@dataclass
class API_MANAGER(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	EDITAPI: str = 'edit-api'
	STARTAPI: str = 'start-api'
	STOPAPI: str = 'stop-api'
	INFO: str = 'info'
	RESTARTAPI: str = 'restart-api'


@dataclass
class MINIMALHTML(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	ADD_GROUP: str = 'add_group'
	ADD_COLLECTION_TO_GROUP: str = 'add_collection_to_group'
	GENERATE_HTML: str = 'generate_html'
	FUSE_TO_STRING: str = 'fuse_to_string'


@dataclass
class RESTRICTOR(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'


@dataclass
class SOCKETMANAGER(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	CREATE_SOCKET: str = 'create_socket'
	TBSOCKETCONTROLLER: str = 'tbSocketController'
	VERSION: str = 'Version'


@dataclass
class WELCOME(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	ANIMATION: str = 'Animation'
	ANIMATION1: str = 'Animation1'
	VERSION: str = 'Version'
	API_VERSION: str = 'api_Version'
	PRINTT: str = 'printT'
	WEBINSTALL: str = 'webInstall'


@dataclass
class VIRTUALIZATIONTOOL(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	CREATE: str = 'create'
	SETAC: str = 'set-ac'
	LIST: str = 'list'
	SHEAR: str = 'shear'


@dataclass
class QUICKNOTE(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	ADD: str = 'ADD'
	VIEW: str = 'VIEW'
	SAVE_INBOX: str = 'Save_inbox'
	GET_INBOX: str = 'Get_inbox'
	SAVE_INBOX_API: str = 'save_inbox_api'
	GET_INBOX_API: str = 'get_inbox_api'
	SAVE_TYPES_API: str = 'save_types_api'
	GET_TYPES_API: str = 'get_types_api'


@dataclass
class CLOUDM(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	API_VERSION: str = 'api_Version'
	NEW: str = 'NEW'
	UPLOAD: str = 'upload'
	DOWNLOAD: str = 'download'
	FIRSTWEBCONNECTION: str = 'first-web-connection'
	CREATEACCOUNT: str = 'create-account'
	LOGIN: str = 'login'
	API_CREATE_USER: str = 'api_create_user'
	API_LOG_IN_USER: str = 'api_log_in_user'
	API_LOG_OUT_USER: str = 'api_log_out_user'
	API_EMAIL_WAITING_LIST: str = 'api_email_waiting_list'
	API_VALIDATE_JWT: str = 'api_validate_jwt'
	VALIDATE_JWT: str = 'validate_jwt'
	DOWNLOAD_API_FILES: str = 'download_api_files'
	#UPDATECORE: str = '#update-core'
	WSGETI: str = 'wsGetI'
	VALIDATE_WS_ID: str = 'validate_ws_id'
	MODINSTALLER: str = 'mod-installer'
	SYSTEM_INIT: str = 'system_init'
	MODREMOVER: str = 'mod-remover'
	CLOSE_USER_INSTANCE: str = 'close_user_instance'
	GET_USER_INSTANCE: str = 'get_user_instance'
	SET_USER_LEVEL: str = 'set_user_level'


@dataclass
class WEBSOCKETMANAGER(Enum):
	APP_INSTANCE: str = 'app_instance'
	APP_INSTANCE_TYPE: str = 'app_instance_type'
	VERSION: str = 'Version'
	CONNECT: str = 'connect'
	DISCONNECT: str = 'disconnect'
	SEND_MESSAGE: str = 'send_message'
	LIST: str = 'list'
	GET: str = 'get'
	SRQW: str = 'srqw'
	CONSTRUCT_RENDER: str = 'construct_render'