[package]
name = "tb-parser"
version.workspace = true
edition.workspace = true

[dependencies]
tb-core = { path = "../tb-core" }
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

