name: docs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-python@v4
                with:
                    python-version: 3.11
            -   run: python -m pip install --upgrade pip
            -   run: pip install mkdocs-material mkdocstrings mkdocstrings-python-legacy mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install --user --no-cache-dir Cython
                    pip install --user uv
                    python -m uv venv --python 3.11
                    python -m uv pip install .[isaa]
            -   name: Install toolboxv2 package
                run: pip install -e .[isaa]
            -   name: Debug mkdocstrings import
                run: |
                    python -c "import toolboxv2; print('toolboxv2 loaded successfully')"
            -   name: Add project to PYTHONPATH
                run: echo "PYTHONPATH=$GITHUB_WORKSPACE/toolboxv2" >> $GITHUB_ENV
            -   run: mkdocs gh-deploy --force
