name: docs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-python@v4
                with:
                    python-version: 3.11
            -   run: python -m pip install --upgrade pip
            -   run: pip install mkdocs-material mkdocstrings mkdocstrings-python-legacy mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install --user --no-cache-dir Cython
                    pip install --user -r requirements.txt
                    pip install --user -r requirements_dev.txt
            -   name: Install toolboxv2 package
                run: pip install -e .
            -   name: Debug mkdocstrings import
                run: |
                    python -c "import toolboxv2; print('toolboxv2 loaded successfully')"
            -   run: mkdocs gh-deploy --force
